name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  unix:
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    timeout-minutes: 45

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    env:
      USE_HARD_LINKS: false
      DISPLAY: ":99.0"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 12.9.1

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          check-latest: true
          cache: 'pnpm'

      # Workaround: Fix native build failure due to outdated node-gyp version.
      - name: Fix node-gyp
        run: |
          npm install --global node-gyp@latest
          npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}
          node-gyp install
        shell: pwsh
      - name: Fix No module named 'distutils'
        if: runner.os == 'macOS'
        run: |
          brew install python-setuptools

      - name: Cache Electron
        uses: actions/cache@v4
        with:
          path:  ${{ env.HOME }}/.cache/electron
          key: ${{ runner.os }}-electron-cache-v2-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Cache Electron-Builder
        uses: actions/cache@v4
        with:
          path: ${{ env.HOME }}/.cache/electron-builder
          key: ${{ runner.os }}-electron-builder-cache-v2-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build page_app
        run: pnpm --filter file-share-app run build:desktop
        shell: bash

      - name: Build page_web
        run: pnpm --filter file-share-web run build
        shell: bash

      - name: Build electron
        working-directory: ./electron
        run: |
          ARCH=$(uname -m)
          echo $RUNNER_OS
          echo $ARCH
          if [ "$RUNNER_OS" == "Linux" ]; then
            pnpm run release:linux
          elif [ "$RUNNER_OS" == "macOS" ]; then
            pnpm run release:mac
          else
            echo "$RUNNER_OS not supported"
            exit 1
          fi

      - name: Echo build info
        working-directory: ./electron
        run: ls -la ./build

      - name: Release linux
        uses: softprops/action-gh-release@v2
        if: runner.os == 'Linux'
        with:
          body_path: changelogs/${{ github.ref_name }}.md
          files: |
            electron/build/fileshare-linux-amd64.deb

      - name: Release mac
        uses: softprops/action-gh-release@v2
        if: runner.os == 'macOS'
        with:
          body_path: changelogs/${{ github.ref_name }}.md
          files: |
            electron/build/fileshare-mac-arm64.dmg
            electron/build/fileshare-mac-x64.dmg

  windows:
    runs-on: windows-latest
    continue-on-error: false
    timeout-minutes: 45

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 12.9.1

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          check-latest: true
          cache: 'pnpm'

      # Workaround: Fix native build failure due to outdated node-gyp version.
      - name: Fix node-gyp
        run: |
          npm install --global node-gyp@latest
          npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}
          node-gyp install
        shell: pwsh

      - name: Cache Electron
        uses: actions/cache@v4
        with:
          path: ${{ env.LOCALAPPDATA }}\electron\Cache
          key: ${{ runner.os }}-electron-cache-v2-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Cache Electron-Builder
        uses: actions/cache@v4
        with:
          path: ${{ env.LOCALAPPDATA }}\electron-builder\cache
          key: ${{ runner.os }}-electron-builder-cache-v2-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build page_app
        run: pnpm --filter file-share-app run build:desktop
        shell: bash

      - name: Build page_web
        run: pnpm --filter file-share-web run build
        shell: bash

      - name: Build electron
        working-directory: ./electron
        run: pnpm run release:win
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: changelogs/${{ github.ref_name }}.md
          files: |
            electron/build/fileshare-setup-win-ia32.exe
            electron/build/fileshare-setup-win-x64.exe
